[package]
name = "ir"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.0"
regex = "1.10.2"
rsnltk = "0.1.3"
rust-stemmers = "1.2.0"
serde = { version = "1.0.193", features = ["derive"] }
